config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/landing'
  get 'static_pages/team'
  get 'static_pages/contact'


  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'game_sheets#index'
    end
    unauthenticated do
      root 'static_pages#landing'
    end
  end

  resources :users do
    resources :avatars, only: [:create]
    resources :addresses, except: [:show]
    resources :orders, only: [:index, :show, :create, :update] do
      resources :shippings, only: [:show, :update]
    end
    resources :subscriptions, except: [:show]
  end

  resources :game_sheets, only: [:index, :show] do
    resources :game_pictures, only: [:create]
  end

  namespace :admin do
    root to: 'games#index'
    resources :games, except: [:show, :destroy]
    resources :game_sheets, except: [:show, :destroy]
    resources :users, except: [:show, :new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :games, only: [:update]

  namespace :stripe do
    resources :checkouts
    get 'checkout/success', to: 'checkouts#success', as: 'checkouts_success'
    get 'checkout/cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    post 'checkout/webhook', to: 'checkouts#webhook'
    resources :checkoutorders
    get 'checkoutorder/success', to: 'checkoutorders#success', as: 'checkoutorders_success'
    get 'checkoutorder/cancel', to: 'checkoutorders#cancel', as: 'checkoutorders_cancel'
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :create_cart
  after_create :send_welcome_email

  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  has_one_attached :avatar, dependent: :destroy

  def remember_me
    true
  end

  def thumbnail
    return self.avatar.variant(resize: '300x300!').processed 
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def already_completed_profile?
    if (self.first_name != nil) && (self.last_name != nil) && (self.date_of_birth != nil) && (self.phone_number != nil) && (self.gender != nil)
      return true
    end
    return false
  end

  def already_subscribed?
    self.subscriptions.each do |subscription|
      return true if subscription.active?
    end
    return false
  end

  def already_has_an_address?
    self.addresses.each do |address|
      return true if address != nil
    end
    return false
  end

  private

  def create_cart
    self.carts.create
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all

    @column_names = ["id", "email","first_name", "last_name", "date_of_birth", "phone_number", "gender", "stripe_id", "is_admin?"]
    
    @column_names_non_visible = ["encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "created_at", "updated_at"]

    @urls_d = []
    @urls_e = []
    @users.each do |user|
      @urls_d << admin_user_path(user)
      @urls_e << edit_admin_user_path(user)
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "le profil de l'ustilisateur n°#{@user.id} a été mis à jour"
      redirect_to(admin_users_path)
    else
      flash.now[:alert] = "Oups ! Les modifications de l'utilistateur n°#{@user.id} n'ont pas put être enregistré"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "l'utilisateur a bien été supprimer"
    redirect_to admin_users_path
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :phone_number, :gender, :date_of_birth, :stripe_id, :is_admin?)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :good_user?

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Bien joué ! Ton profil a été modifié 🎉"
      redirect_to(user_path(@user))
    else
      flash.now[:alert] = "Oups ! On ne peut pas modifier ton profil pour les raisons suivantes :"
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :phone_number, :gender, :date_of_birth)
  end

  def good_user?
    user_id = params[:id]
    check_user(user_id)
  end
end

app/views/users/_progress_user_profile_completion.html.erb
<!-- Progress bar - Level 3 -->

<% if (current_user.already_completed_profile?) && (current_user.already_has_an_address?) && (current_user.already_subscribed?) %>

  <div class="progress-wrapper mb-3 mb-md-5">

    <div class="progress-info info-xl d-block d-md-flex">
      <div class="progress-label">
        <h2 class="h4 text-dark">Progression du profil</h2>
      </div>
      <div>
        <span class="text-gray h4">100%</span>
      </div>
    </div>
    
    <div class="progress progress-lg my-4 my-md-0">
      <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; animation: 3s ease 0s 1 normal none running animate-positive; opacity: 1;"></div>
    </div>

  </div>

<!-- Progress bar - Level 2 -->

<% elsif ((current_user.already_completed_profile?) && (current_user.already_has_an_address?)) || ((current_user.already_completed_profile?) && (current_user.already_subscribed?)) || ((current_user.already_has_an_address?) && (current_user.already_subscribed?)) %>

  <div class="progress-wrapper mb-3 mb-md-5">

    <div class="progress-info info-xl d-block d-md-flex">
      <div class="progress-label">
        <h4 class="text-dark">Progression du profil</h4>
      </div>
      <div>
        <span class="text-gray h4">75%</span>
      </div>
    </div>
    
    <div class="progress progress-lg my-4 my-md-0">
      <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%; animation: 3s ease 0s 1 normal none running animate-positive; opacity: 1;"></div>
    </div>

  </div>

<!-- Progress bar - Level 1 -->

<% elsif (current_user.already_completed_profile?) || (current_user.already_has_an_address?) || (current_user.already_subscribed?) %>

  <div class="progress-wrapper mb-3 mb-md-5">

    <div class="progress-info info-xl d-block d-md-flex">
      <div class="progress-label">
        <h4 class="text-dark">Progression du profil</h4>
      </div>
      <div>
        <span class="text-gray h4">30%</span>
      </div>
    </div>
    
    <div class="progress progress-lg my-4 my-md-0">
      <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%; animation: 3s ease 0s 1 normal none running animate-positive; opacity: 1;"></div>
    </div>

  </div>

  <!-- Progress bar - Level 0 -->

  <% else %>

  <div class="progress-wrapper mb-3 mb-md-5">

    <div class="progress-info info-xl d-block d-md-flex">
      <div class="progress-label">
        <h4 class="text-dark">Progression du profil</h4>
      </div>
      <div>
        <span class="text-gray h4">20%</span>
      </div>
    </div>
    
    <div class="progress progress-lg my-4 my-md-0">
      <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%; animation: 3s ease 0s 1 normal none running animate-positive; opacity: 1;"></div>
    </div>

  </div>

<% end %>

app/views/users/edit.html.erb
<div class="section section-lg bg-soft">
  <div class="container">
    <div class="row pt-5 pt-md-0">

      <!-- Profile menu with recurring paths -->

     
        <%= render 'shared/menu_profil' %>
      

      <!-- Customized form for user info edition -->

      <div class="col-12 col-lg-8">
              
        <div class="card border-light p-2">

          <div class="card-body p-2">
          
            <h3 class="my-4 font-weight-normal text-center">Éditer mon profil</h3>

            

            <%= form_for @user do |f| %>
      
              <div class="form-group">
                <%= f.label "Genre", class: "mb-2" %>                                     
                <%= f.select :gender, ['', 'Femme', 'Homme', 'Autre'], {}, class: 'form-control' %>
              </div>
                              
              <div class="form-group">
                <%= f.label "Prénom", class: "mb-2" %>
                <%= f.text_field :first_name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label "Nom de famille", class: "mb-2" %>
                <%= f.text_field :last_name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label "Date de naissance", class: "mb-2" %>
                <%= f.date_field :date_of_birth, class:"form-control" %>
              </div>

              <div class="form-group">
                  <%= f.label "Numéro de téléphone", class: "mb-2" %>
                  <%= f.text_field :phone_number, class:"form-control"%>
              </div>

              <div class="form-group">
                <%= f.label :add_avatar, "Optionnel - Ajouter une photo de profil", class: "mb-2 font-italic" %>
                <%= f.file_field :avatar, class: "form-control overflow-hidden" %>
              </div>

              <div class="actions mt-5 mb-3">
                <%= f.submit "Mettre à jour", class: "btn btn-lg btn-primary btn-block" %>
              </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
       

app/views/users/show.html.erb
<div class="section section-lg bg-soft">
  <div class="container">
    <div class="row pt-5 pt-md-0">
      
        <%= render 'shared/menu_profil' %>  
     

      <div class="col-12 col-lg-8">
        <div class="card rounded border border-light">
          <div class="card-body p-3 p-md-5">
            <h2>Bienvenue sur PulpoLudo !</h2> 
            <%= render 'progress_user_profile_completion' %>
            <%= render 'shared/cta_profile_completion(user_profile)' %>
            <% if @user.already_subscribed? && @user.already_has_an_address? && @user.already_completed_profile? %>
              <%= link_to "Aller sur mon panier", cart_path(@user), class: "btn btn-primary my-3 text-center" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>