config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/landing'
  get 'static_pages/team'
  get 'static_pages/contact'


  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'game_sheets#index'
    end
    unauthenticated do
      root 'static_pages#landing'
    end
  end

  resources :users do
    resources :avatars, only: [:create]
    resources :addresses, except: [:show]
    resources :orders, only: [:index, :show, :create, :update] do
      resources :shippings, only: [:show, :update]
    end
    resources :subscriptions, except: [:show]
  end

  resources :game_sheets, only: [:index, :show] do
    resources :game_pictures, only: [:create]
  end

  namespace :admin do
    root to: 'games#index'
    resources :games, except: [:show, :destroy]
    resources :game_sheets, except: [:show, :destroy]
    resources :users, except: [:show, :new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :games, only: [:update]

  namespace :stripe do
    resources :checkouts
    get 'checkout/success', to: 'checkouts#success', as: 'checkouts_success'
    get 'checkout/cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    post 'checkout/webhook', to: 'checkouts#webhook'
    resources :checkoutorders
    get 'checkoutorder/success', to: 'checkoutorders#success', as: 'checkoutorders_success'
    get 'checkoutorder/cancel', to: 'checkoutorders#cancel', as: 'checkoutorders_cancel'
  end
  
end

app/views/shared/_cta_info_missing(user_cart).html.erb
<div class="text-center my-4">
  <h5>Il nous manque quelques infos pour que vous puissiez passer commande des 5 jeux 😬</h5>
  <h5>Vous pourrez revenir sur votre panier juste après !</h5>
</div>

<div class="container d-flex justify-content-center my-3">
  <% unless current_user.already_completed_profile? %>
    <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
      <%= image_tag "illustrations/user_profile.png", class: "my-2", style: "max-height:100px" %>
      <%= active_link_to "Compléter mon profil →", edit_user_path(current_user), class: "btn btn-primary my-2" %>
    </div>
  <% end %>
  <% unless current_user.already_has_an_address? %>
    <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
      <%= image_tag "illustrations/feature-1.png", class: "my-2", style: "max-height:100px" %>
      <%= active_link_to "Ajouter mon adresse →", new_user_address_path(current_user), class: "btn btn-primary my-2" %>
    </div>
  <% end %>
</div>

app/views/shared/_cta_profile_completion(user_profile).html.erb
<div class="row">
  <% unless current_user.already_completed_profile? %>
    <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
      <%= image_tag "illustrations/user_profile.png", class: "my-2", style: "max-height:100px" %>
      <%= active_link_to "Compléter mon profil →", edit_user_path(current_user), class: "btn btn-primary my-2" %>
    </div>
  <% end %>

  <% unless current_user.already_subscribed? %>
    <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
      <%= image_tag "illustrations/easy-transaction.png", class: "my-2", style: "max-height:100px" %>
      <%= link_to "Démarrer mon abonnement →", new_stripe_checkout_path, class: "btn btn-primary my-2", remote: true %>
    </div>
  <% end %>

  <% unless current_user.already_has_an_address? %>
    <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
      <%= image_tag "illustrations/feature-1.png", class: "my-2", style: "max-height:100px" %>
      <%= active_link_to "Ajouter mon adresse →", new_user_address_path(current_user), class: "btn btn-primary my-2" %>
    </div>
  <% end %>
</div>

app/views/shared/_cta_profile_completion.html.erb
<div class="container">
  <div class="row">

    <% unless current_user.already_completed_profile? %>
      <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
        <%= image_tag "illustrations/user_profile.png", class: "my-2", style: "max-height:200px" %>
        <%= active_link_to "Compléter mon profil →", edit_user_path(current_user), class: "btn btn-primary my-2" %>
      </div>
    <% end %>

    <% unless current_user.already_subscribed? %>
      <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
        <%= image_tag "illustrations/easy-transaction.png", class: "my-2", style: "max-height:200px" %>
        <%= button_to "Démarrer mon abonnement →", checkout_create_path(price: 10), class: "btn btn-primary my-2", remote: true %>
      </div>
    <% end %>

    <% unless current_user.already_has_an_address? %>
      <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
        <%= image_tag "illustrations/feature-1.png", class: "my-2", style: "max-height:200px" %>
        <%= active_link_to "Ajouter une adresse →", new_user_address_path(current_user), class: "btn btn-primary my-2" %>
      </div>
    <% end %>

  </div>
</div>

app/views/shared/_cta_subscription(main_index).html.erb
<div class="container d-flex justify-content-center">
    <% unless current_user.already_subscribed? %>
      <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 px-lg-4">
        <%= image_tag "illustrations/easy-transaction.png", class: "my-2", style: "max-height:200px" %>
        <%= link_to "Démarrer mon abonnement →", new_stripe_checkout_path, class: "btn btn-primary my-2", remote: true %>
      </div>
    <% end %>
</div>

app/views/shared/_menu_profil.html.erb
<!-- Navigation related to user profile -->
<div class="col-12 col-md-4 d-none d-lg-block">
    <div class="card border-light p-2">

        <div class="card-body p-2">
            
            <div class="profile-thumbnail small-thumbnail mx-auto">
                <%if current_user.avatar.attached?%>
                  <%= image_tag @user.thumbnail, class: "card-img-top rounded-circle border-white", alt: "photo-de-profil" %>
                <%else%>
                  <%= image_tag 'unnamed.jpg', alt: 'default avatar', class: "card-img-top rounded-circle border-white", alt: "photo-de-profil" %>
                <% end %>
            </div>
            
            <h2 class="h5 font-weight-normal text-center mt-3 mb-0"><%= current_user.first_name %> <%= current_user.last_name %> </h2>
            
            <div class="list-group dashboard-menu list-group-sm mt-4">

                <%= active_link_to user_path(current_user), class: "d-flex list-group-item list-group-item-action", active: :exclusive do %>
                    Général
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>
                   
                <%= active_link_to edit_user_path(current_user), class: "d-flex list-group-item list-group-item-action" do %>
                    Mon profil
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>
                
                <%= active_link_to edit_user_registration_path(current_user), class: "d-flex list-group-item list-group-item-action" do %>
                    Mes informations de connexion
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>
          
                <%= active_link_to user_addresses_path(current_user), class: "d-flex list-group-item list-group-item-action" do %>
                    Mes adresses
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>
                
                <%= active_link_to user_subscriptions_path(current_user), class: "d-flex list-group-item list-group-item-action" do %>
                    Gérer mon abonnement
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>

                <% if current_order != nil %>
                    <%= active_link_to user_order_path(current_user, current_order), class: "d-flex list-group-item list-group-item-action",  active: :exclusive do %>
                        Ma commande en cours
                        <span class="icon icon-xs ml-auto">
                        <span class="fas fa-chevron-right">
                        </span>
                        </span>
                    <% end %>
                <% end %>

                <%= active_link_to user_orders_path(current_user), class: "d-flex list-group-item list-group-item-action", active: :exclusive do %>
                    Mes anciennes commandes
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %>

                <%= active_link_to destroy_user_session_path, method: :delete, class: "d-flex list-group-item list-group-item-action" do %>
                    Se déconnecter
                    <span class="icon icon-xs ml-auto">
                    <span class="fas fa-chevron-right">
                    </span>
                    </span>
                <% end %> 
                    
            </div>
        </div>
    </div>
</div>

<div class="col-12 d-lg-none">
    <div class="card bg-white border-light mb-4 mb-lg-5">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-10 d-flex">
                    
                    <%= active_link_to user_path(current_user), class: "list-group-item list-group-item-action border-0", active: :exclusive do %>
                        Général
                    <% end %>
                    
                    <%= active_link_to edit_user_path(current_user), class: "list-group-item list-group-item-action border-0 " do %>
                        Profil
                    <% end %>
                    
                    <%= active_link_to edit_user_registration_path(current_user), class: "list-group-item list-group-item-action d-none d-sm-block border-0 " do %>
                        Informations
                    <% end %>
            
                    <%= active_link_to user_addresses_path(current_user), class: "list-group-item list-group-item-action d-none d-md-block border-0 " do %>
                        Adresses
                    <% end %>
                </div>
                <div class="col-2 d-flex justify-content-center">
                    <div class="btn-group dropleft dropdown">
                        <div class="btn btn-link dropdown-toggle dropdown-toggle-split mr-2 m-0 p-0" type="button" data-toggle="dropdown" id="dropdownProfil" aria-haspopup="true" aria-expanded="false">
                            <span class="icon icon-sm">
                                <span class="fas fa-ellipsis-h icon-secondary fa-lg"></span>
                            </span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </div>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownProfil">

                        <div class="dropdown-item">

                            <%= active_link_to edit_user_registration_path(current_user), class: "list-group-item list-group-item-action d-sm-none border-0 " do %>
                                Informations
                            <% end %>

                        </div>

                        <div class="dropdown-item">
          
                            <%= active_link_to user_addresses_path(current_user), class: "list-group-item list-group-item-action d-md-none border-0" do %>
                                Adresses
                            <% end %>

                        </div>

                        <div class="dropdown-item">
                            
                            <%= active_link_to user_subscriptions_path(current_user), class: "list-group-item list-group-item-action  border-0 " do %>
                                Gérer mon abonnement
                            <% end %>
                         </div>
                         <div class="dropdown-item">
                        
                            <% if current_order != nil %>
                                <%= active_link_to user_order_path(current_user, current_order), class: "list-group-item list-group-item-action  border-0",  active: :exclusive do %>
                                Ma commande en cours
                                <% end %>
                            <% end %>

                        </div>
                        <div class="dropdown-item">
                        
                            <%= active_link_to user_orders_path(current_user), class: "list-group-item list-group-item-action border-0", active: :exclusive do %>
                                 Mes anciennes commandes
                            <% end %>
                        </div>

                        <div class="dropdown-item">

                        
                            <%= active_link_to destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action border-0" do %>
                                Se déconnecter
                             <% end %> 
                        </div>
                
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>