config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/landing'
  get 'static_pages/team'
  get 'static_pages/contact'


  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'game_sheets#index'
    end
    unauthenticated do
      root 'static_pages#landing'
    end
  end

  resources :users do
    resources :avatars, only: [:create]
    resources :addresses, except: [:show]
    resources :orders, only: [:index, :show, :create, :update] do
      resources :shippings, only: [:show, :update]
    end
    resources :subscriptions, except: [:show]
  end

  resources :game_sheets, only: [:index, :show] do
    resources :game_pictures, only: [:create]
  end

  namespace :admin do
    root to: 'games#index'
    resources :games, except: [:show, :destroy]
    resources :game_sheets, except: [:show, :destroy]
    resources :users, except: [:show, :new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :games, only: [:update]

  namespace :stripe do
    resources :checkouts
    get 'checkout/success', to: 'checkouts#success', as: 'checkouts_success'
    get 'checkout/cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    post 'checkout/webhook', to: 'checkouts#webhook'
    resources :checkoutorders
    get 'checkoutorder/success', to: 'checkoutorders#success', as: 'checkoutorders_success'
    get 'checkoutorder/cancel', to: 'checkoutorders#cancel', as: 'checkoutorders_cancel'
  end
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :games, dependent: :nullify

  enum status: {current_cart:"panier actuel", send_cart:"panier en location", issus:"probleme"}

  validates :status,
    presence: true,
    inclusion: {in: statuses.keys}

  def already_present(game_to_test)
    self.games.each do |game|
      return true if game.game_sheet.id == game_to_test.game_sheet.id
    end
    return false
  end

  def full_cart?
    self.games.size >= 5
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  include CurrentCart
  before_action :authenticate_user!
  before_action :good_user?
  before_action :subscribed?

  def show
    @user = current_user
    @cart = Cart.find(params[:id])
    @games_in_cart = @cart.games

    game_sheets_in_cart = []
    @games_in_cart.each {|g| game_sheets_in_cart << g.game_sheet}
    @game_sheets_rand = GameSheet.all.reject {|game_sheet| game_sheets_in_cart.include?(game_sheet) }.sample(3)
  end

  def update
    @game_sheet = GameSheet.find(params[:game_sheet_id])
    @cart = Cart.find(params[:id])
    @game = @game_sheet.games.in_stock.sample

    if @cart.full_cart?
      flash[:alert] = "Tu as déjà ajouté 5 jeux à ton abonnement"
      redirect_to root_path
    elsif @cart.already_present(@game)
      flash[:alert] = "Tu ne peux pas louer deux exemplaires du même jeu"
      redirect_to root_path
    else
      @game.update(cart: current_cart)
      @game.leased!
      flash[:notice] = "Ton jeu a bien été ajouté à ton abonnement. Pense à valider ton panier !"
      redirect_to root_path
    end
  end


  private

  def good_user?
    user_id = Cart.find(params[:id]).user_id
    check_user(user_id)
  end

  def subscribed?
    @user = Cart.find(params[:id]).user
    unless @user.already_subscribed?
      flash[:notice] = "Pour pouvoir ajouter un jeu à ton panier tu dois être abonné"
      redirect_to user_subscriptions_path(@user)
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper

  def current_cart
    current_user.carts.last
  end
end

app/views/carts/show.html.erb
<div class="section section-lg bg-soft">
  <div class="container">
    <h1 class="pt-5 pt-md-0 my-5 text-center"><i class="fas fa-cart-arrow-down"></i> Mon panier</h1>
                          

    <%if @cart.send_cart?%>
      <div class="row">
        <div class="col-12">
          <h6 class="text-center"> Tu as déjà commandé 5 jeux. Si tu veux en recomander 5 nouveaux il te faut d'abord nous renvoyer les 5 que tu as chez toi. <br>
          Lorsque que nous les reçevrons nous t'enverons un mail pour te signaler que tu peux en commander 5 nouveaux. </h6>
          <%= link_to "Ma commande actuelle", user_order_path(current_user, current_order), :class => "ml-3 col-auto btn btn-primary my-auto" %>
        </div>
      </div>
    <% else %>
      <% unless @cart.games.empty? %>  
        <div class="row">
          <div class="col-12">
            <div class="table-responsive align-middle">                            
              <table class="table mb-0 align-middle">
                <thead class="bg-light border-top">
                  <tr>
                    <th scope="row" class="border-0 text-left">
                      Image du jeu
                    </th>
                    <th scope="row" class="border-0">
                      Nom du jeu
                    </th>                                         
            
                    <th scope="row" class="border-0">
                      
                    </th>
                  </tr>
                </thead>
                <% @cart.games.each do |game| %>
                  <tbody>
                    <tr>
                      <td>
                        <%if game.game_sheet.game_picture.attached?%>
                          <%= image_tag game.game_sheet.game_picture, :alt => "game img", class:"card-img p-2 rounded-xl", style: "height: 300px; width: auto" %>
                        <%else%>
                          <img style= "height: 100px; width: auto" src="<%= asset_path( 'game-index-background4.jpg' ) %>" />
                        <% end %>
                      </td>
                      <td class="align-middle"> 
                        <%= game.game_sheet.title %>
                      </td>                          
                      <td class="align-middle text-right">
                        <a href="<%= game_path(game.id) %>" class="btn btn-light" data-confirm="êtes-vous sur?" data-method="PATCH">Supprimer du panier</a>
                      </td>                                        
                    </tr>                  
                  </tbody>
                <%end%>  
              </table>
            </div>
          </div>
        </div>
        <%if @cart.full_cart?%>
          <div class="row">
            <div class="col-12">
              <% unless @user.already_has_an_address? && @user.already_completed_profile? %>
                <%= render 'shared/cta_info_missing(user_cart)' %>
              <%else%>  
                <div class="d-flex justify-content-end text-right mb-4 py-4">
                  <div class="mt-4">
                    <table class="d-flex justify-content-end table table-clear text-center">
                      <tbody>
                        <tr>
                          <td class="left">
                            <strong>Frais de port</strong>
                          </td>
                          <td class="right">10€</td>
                        </tr>
                        
                        <tr>
                          <td colspan="2" class="right"> 
                            <%= link_to "Passer commande", new_stripe_checkoutorder_path(total: 10), class: "btn btn-primary my-3", remote: true %>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
        <%else%>
          <div class="d-flex justify-content-end text-right mb-4 py-4">
            <div class="mt-4">
              <br>
              <br>
              <p class="text-center">Rajoute encore <strong> <%= 5- @games_in_cart.size %> jeux</strong> à ton panier pour pouvoir commander</p>
              <br>
              <br>
            </div>
          </div>

          <div>
            <div class="col-12">
              <h4 class="mb-5 font-weight-bold">Voici une liste de jeux qui pourrais t'intéresser :</h4>
            </div>

            <div class="tab-pane fade show active pl-3" id="link-example-14" role="tabpanel" aria-labelledby="tab-link-example-14">
              <div class="row">
                <!-- Cards-->

                <% @game_sheets_rand.each do |game_sheet| %>

                  <div class="col-12 col-sm-6 col-lg-4">
                    <div class="card border-light mb-4 animate-up-5">
                      <a href="<%= game_sheet_path(game_sheet.id) %>">
                        <%if game_sheet.game_picture.attached?%>
                          <%= image_tag game_sheet.game_picture, :alt => "game img", class:"card-img p-2 rounded-xl", style: "height: 300px; width: auto" %>
                        <%else%>
                          <%= image_tag asset_path( 'game-index-background4.jpg' ), :alt => "game img", class:"card-img p-2 rounded-xl", style: "height: 300px; width: auto" %>
                        <% end %>
                      </a>

                      <div class="card-body">
                        <a href="<%= game_sheets_path(@game_sheets) %>">
                          <h4 class="h5"><%= game_sheet.title %></h4>
                        </a>
                        <div class="d-flex my-4">
                            <span class="star fas fa-star text-warning"></span> 
                            <span class="star fas fa-star text-warning"></span> 
                            <span class="star fas fa-star text-warning"></span> 
                            <span class="star fas fa-star text-warning"></span> 
                            <span class="star fas fa-star text-warning"></span>
                            <span class="badge badge-pill badge-primary ml-2">5.0</span>
                        </div>
                          <ul class="list-group mb-3">
                            <li class="list-group-item small p-0"><span class="fas fa-users mr-2"></span><%= game_sheet.nb_players %> joueurs</li>
                            <li class="list-group-item small p-0"><span class="fas fa-birthday-cake mr-2"></span><%= game_sheet.age_min %>+ ans</li>
                            <li class="list-group-item small p-0"><span class="fas fa-car-battery mr-2"></span>difficulté <%= game_sheet.difficulty %></li>
                          </ul>
                      </div>
                    </div>
                  </div>
                <% end %>
              <!-- End of Card -->
              </div>
            </div>
          </div>

        <%end%>
      <% else %>
        <div class="row">
          <div class="col-12">
            <h6 class="text-center"> Ton panier est vide. Ajoute 5 jeux pour pouvoir les commander ! </h6>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>