config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/landing'
  get 'static_pages/team'
  get 'static_pages/contact'


  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'game_sheets#index'
    end
    unauthenticated do
      root 'static_pages#landing'
    end
  end

  resources :users do
    resources :avatars, only: [:create]
    resources :addresses, except: [:show]
    resources :orders, only: [:index, :show, :create, :update] do
      resources :shippings, only: [:show, :update]
    end
    resources :subscriptions, except: [:show]
  end

  resources :game_sheets, only: [:index, :show] do
    resources :game_pictures, only: [:create]
  end

  namespace :admin do
    root to: 'games#index'
    resources :games, except: [:show, :destroy]
    resources :game_sheets, except: [:show, :destroy]
    resources :users, except: [:show, :new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :games, only: [:update]

  namespace :stripe do
    resources :checkouts
    get 'checkout/success', to: 'checkouts#success', as: 'checkouts_success'
    get 'checkout/cancel', to: 'checkouts#cancel', as: 'checkouts_cancel'
    post 'checkout/webhook', to: 'checkouts#webhook'
    resources :checkoutorders
    get 'checkoutorder/success', to: 'checkoutorders#success', as: 'checkoutorders_success'
    get 'checkoutorder/cancel', to: 'checkoutorders#cancel', as: 'checkoutorders_cancel'
  end
  
end

app/views/admin/layouts/_navbar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4 pb-100">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <%= image_tag 'logo/COULEUR/Rendu_final_LOGO_COURT_COULEUR_FOND_SOMBRE.png', class: "brand-image img-circle elevation-3", :style => "opacity: .8" %>
      <span class="brand-text font-weight-light">Admin PulpoLudo</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <%if current_user.avatar.attached?%>
            <%= image_tag(current_user.thumbnail, :alt => "User Image", class: "img-circle elevation-2")%>
          <%else%>
            <%= image_tag('unnamed.jpg', class: "img-circle elevation-2", alt: "User Image")%>
          <% end %>
        </div>
        <div class="info">
          <a href="#" class="d-block"><%= current_user.full_name%></a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div><div class="sidebar-search-results"><div class="list-group"><a href="#" class="list-group-item">
        <div class="search-title">
          <b class="text-light"></b>N<b class="text-light"></b>o<b class="text-light"></b> <b class="text-light"></b>e<b class="text-light"></b>l<b class="text-light"></b>e<b class="text-light"></b>m<b class="text-light"></b>e<b class="text-light"></b>n<b class="text-light"></b>t<b class="text-light"></b> <b class="text-light"></b>f<b class="text-light"></b>o<b class="text-light"></b>u<b class="text-light"></b>n<b class="text-light"></b>d<b class="text-light"></b>!<b class="text-light"></b>
        </div>
        <div class="search-path">
          
        </div>
      </a></div></div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to admin_root_path, class: "nav-link" do%>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="nav-header">Gestion de la Base de Donnée</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Games
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to admin_games_path, class:"nav-link" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Liste des jeux
                  </p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_game_path, class:"nav-link" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Nouveau jeu
                  </p>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Games Sheets
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to admin_game_sheets_path, class:"nav-link" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Liste des fiches de jeux
                  </p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_game_sheet_path, class:"nav-link" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Nouvelle fiche de jeu
                  </p>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Users
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to admin_users_path, class:"nav-link" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Liste des utilisateurs
                  </p>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Tags
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Thème</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Mécanique</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Auteur</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Illustrateur</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Editeur</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-header">Gestion des envois</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Games to send
                <span class="badge badge-info right">2</span>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PulpoludoThp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">

    <%= favicon_link_tag asset_path('logo/FAVICON/favicon-logo-court-couleur-recentré.png') %>

    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>

    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="sidebar-mini" style="height: auto;">
    <div class="wrapper">

      <%= render 'admin/layouts/navbar' %>
      <div class="content-wrapper">
        <%= yield %>
      </div>

    </div>
  </body>
</html>